import logging
import json
import requests
import config


def confluence_create_page(title, content, parent_page_id):
    # describe json query
    new_page_json_query_string = """
       {
           "type": "page",
           "title": "DEFAULT PAGE TITLE",
           "ancestors": [
               {
               "id": 111
               }
           ],
           "space": {
               "key": "DEFAULT KEY"
           },
           "body": {
               "storage": {
                   "value": "DEFAULT PAGE CONTENT",
                   "representation": "storage"
               }
           }
       }
       """

    # load json from string
    new_page_json_query = json.loads(new_page_json_query_string)

    # the key of Confluence space for content publishing
    new_page_json_query['space']['key'] = config.CONFLUENCE_SPACE

    # check of input of the ParentPageID
    if parent_page_id is None:
        new_page_json_query['ancestors'][0]['id'] = config.CONFLUENCE_PARENT_ID  # this is the root of out pages tree
    else:
        new_page_json_query['ancestors'][0]['id'] = str(parent_page_id)  # this is the branch of our tree

    new_page_json_query['title'] = title

    # add content if the page from the input parameter
    new_page_json_query['body']['storage'][
        'value'] = "<p style=\"background-color:#e7be17;\">This page is autogenerated" + content

    logging.info("Create new page: " + new_page_json_query['title'])
    logging.debug("with content: " + new_page_json_query['body']['storage']['value'])
    logging.debug(json.dumps(new_page_json_query, indent=4, sort_keys=True))

    # make call to create new page
    logging.debug("Calling URL: " + config.CONFLUENCE_BASE_URL + "content/")

    response = requests.post(
        url=config.CONFLUENCE_BASE_URL + "content/",
        json=new_page_json_query,
        headers=config.CONFLUENCE_AUTH_HEADERS,
        verify=False)

    logging.debug(response.status_code)
    if response.status_code == 200:
        logging.info(title + "- Page created successfully")
        logging.debug(json.dumps(json.loads(response.text), indent=4, sort_keys=True))
    else:
        logging.error(title + "- Page has not been created")
    # return new page id
    logging.debug("Returning created page id: " + json.loads(response.text)['id'])
    return json.loads(response.text)['id']
