# config.py

from dotenv import load_dotenv
import os

load_dotenv()

APP_NAME = "Markdown Confluence Transmogrifier"
CONFLUENCE_USER= os.getenv("CONFLUENCE_USER")
CONFLUENCE_PERSONAL_ACCESS_TOKEN = os.getenv("CONFLUENCE_PERSONAL_ACCESS_TOKEN")
CONFLUENCE_API_TOKEN = os.getenv("CONFLUENCE_API_TOKEN")
CONFLUENCE_BASE_URL = os.getenv("CONFLUENCE_BASE_URL")
CONFLUENCE_SPACE = os.getenv("CONFLUENCE_SPACE")
CONFLUENCE_PARENT_ID = os.getenv("CONFLUENCE_PARENT_ID")
LOGGING_LEVEL = os.getenv("LOGGING_LEVEL")
MARKDOWN_DOCUMENTATION_DIRECTORY = os.getenv("MARKDOWN_DOCUMENTATION_DIRECTORY")
DOCUMENTATION_IMAGE_DIRECTORY = os.getenv("DOCUMENTATION_IMAGE_DIRECTORY")
CONFLUENCE_AUTH_HEADERS = None
