name: Self transmogrify docs

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run deployment
        run: |
          docker run --rm \
            -e CONFLUENCE_USER=${{ secrets.CONFLUENCE_USER }} \
            -e CONFLUENCE_API_TOKEN=${{ secrets.CONFLUENCE_API_TOKEN }} \
            -e CONFLUENCE_SPACE=${{ secrets.CONFLUENCE_SPACE }} \
            -e CONFLUENCE_BASE_URL=${{ secrets.CONFLUENCE_BASE_URL }} \
            -e CONFLUENCE_PARENT_ID=${{ secrets.CONFLUENCE_PARENT_ID }} \
            -e MARKDOWN_DOCUMENTATION_DIRECTORY=${{env.MARKDOWN_DOCUMENTATION_DIRECTORY}} \
            -e DOCUMENTATION_IMAGE_DIRECTORY=${{env.DOCUMENTATION_IMAGE_DIRECTORY}} \
            -e LOGGING_LEVEL=${{env.LOGGING_LEVEL}} \
            ghcr.io/cirkonis/markdown-confluence-transmogrifier:latest
